Ли Давид, ДЗ 1, Задача A
David-cripto/Alg_sem3 pull request #1
Opened 2020-10-22 15:14 UTC by David-cripto

https://contest.yandex.ru/contest/19772/run-report/34570292/

2020-10-30 23:10 UTC, egavolk requested changes

2020-10-30 23:10 UTC, egavolk commented on TaskA-string
> +#include <iostream>
Прикрепляй плиз .cpp файлы, неудобно читать без подсветки гитхаба

2020-10-30 23:10 UTC, egavolk commented on TaskA-string
> +	std::vector<int> p = prefix(concat);
Ты считаешь префикс функцию строки длины `O(n+p)` и используешь столько же доп памяти. В контесте разрешено только `O(p)`

2020-10-30 23:10 UTC, egavolk commented on TaskA-string
> +std::vector<int> prefix(std::string s) {
Здесь не надо передавать строку по значению

2020-10-30 23:14 UTC, egavolk commented on TaskA-string
> +using std::string;
Зачем это, если дальше ты пишешь везде `std::string`?

2020-11-16 08:17 UTC, David-cripto commented on TaskA-string
> +	std::vector<int> p = prefix(concat);
fixed

2020-11-16 08:17 UTC, David-cripto commented on TaskA-string
> +#include <iostream>
fixed

2020-11-16 08:18 UTC, David-cripto commented on TaskA-string
> +std::vector<int> prefix(std::string s) {
not fixed(но ты вроде разрешил не редачить :) )

2020-11-16 08:18 UTC, David-cripto commented on TaskA-string
> +using std::string;
fixed

2020-12-05 00:32 UTC, egavolk requested changes
К сожалению, с копипастой не приму( И прикрепляй ссылку на посылку с новым кодом

2020-12-05 00:32 UTC, egavolk commented on Source.cpp
> +		}
Копипаста со строками 14-19

2020-12-05 00:32 UTC, egavolk commented on Source.cpp
> +std::vector<int> prefix(const std::string& pattern, const std::string& str) {
Я только сейчас понял, что название функции не отражает суть. Она должна называться "найти вхождения"

2020-12-15 21:08 UTC, egavolk commented
ping

2020-12-18 06:29 UTC, David-cripto commented on Source.cpp
> +std::vector<int> prefix(const std::string& pattern, const std::string& str) {
fixed

2020-12-18 06:29 UTC, David-cripto commented on Source.cpp
> +		}
fixed

2020-12-20 20:00 UTC, egavolk approved these changes

2020-12-20 20:00 UTC, merged