Ли Давид, ДЗ 1, Задача B
David-cripto/Alg_sem3 pull request #2
Opened 2020-10-22 15:16 UTC by David-cripto

https://contest.yandex.ru/contest/19772/run-report/34564501/

2020-10-30 23:16 UTC, egavolk requested changes

2020-10-30 23:16 UTC, egavolk commented on TaskB-string
> +long long z_fun(std::string s) {
Это не z-функция. Используй https://google.github.io/styleguide/cppguide.html#Function_Names как правило именования функций. Не надо передавать строку по значению

2020-10-30 23:16 UTC, egavolk commented on TaskB-string
> +using std::string;
Зачем, если дальше везде написано `std::string`?

2020-10-30 23:16 UTC, egavolk commented on TaskB-string
> +	}
Копипаста. Два вычисления отличаются только на `+1` и `-1`.

2020-11-16 08:47 UTC, David-cripto commented on TaskB-string
> +long long z_fun(std::string s) {
fixed

2020-11-16 08:47 UTC, David-cripto commented on TaskB-string
> +using std::string;
fixed

2020-11-16 08:47 UTC, David-cripto commented on TaskB-string
> +	}
fixed

2020-12-05 00:36 UTC, egavolk approved these changes
Ок, принято. Предполагалось, что логика с +1 и -1 будет прокинута еще выше(как аргумент твоей функции для манакера), чтобы не создавать 2 массива. Но идею ты уловил

2020-12-05 00:36 UTC, merged

2020-12-05 00:41 UTC, egavolk commented
Так, я поторопился, а у тебя тесты не проходят...

2020-12-05 00:47 UTC, egavolk commented
Создай, плиз, новый пулреквест и прикрепи в него код, проходящий тесты.